spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelservice
    username: root
    password: abrark4961
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
     name: HOTELSERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

